config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin/users', skip: %i[registrations]
  as :admin_user do
    get    '/admin/users/profile',        to: 'devise/registrations#edit',   as: :admin_user_root
    get    '/admin/users/edit(.:format)', to: 'devise/registrations#edit',   as: :edit_admin_user_registration
    patch  '/admin/users(.:format)',      to: 'devise/registrations#update', as: :admin_user_registration
    put    '/admin/users(.:format)',      to: 'devise/registrations#update'
    delete '/admin/users(.:format)',      to: 'devise/registrations#destroy'
    post   '/admin/users(.:format)',      to: 'devise/registrations#create'
  end

  namespace :admin do
    resource :categories, only: [] do
      get  :tree
      get  :childless
      post :sort
      get  :import
      post :preprocess
      post :import, to: 'categories#do_import'
      post :abort_import
      get  :export
      get  :download
      get  ':id/delete_confirmation', to: 'categories#delete_confirmation',
        as: :delete_confirmation
    end
    resources :categories
    resource :concepts, only: [] do
      get  :childless
      get  ':id/delete_confirmation', to: 'concepts#delete_confirmation',
        as: :delete_confirmation
    end
    resources :concepts, except: %i[index]
    resource :data_elements, only: [] do
      get  :orphaned
      post :orphaned, to: 'data_elements#assign_orphaned'
      get  :reindex
      post :reindex, to: 'data_elements#do_reindex'
    end
    resources :data_elements, only: %i[index show]
    resource :import_datasets, only: [] do
      get  'import(/:id)',       to: 'import_datasets#import',
                                 as: :import
      post :preprocess
      get  'recognised/:id',     to: 'import_datasets#recognised',
                                 as: :recognised
      post 'recognised/:id',     to: 'import_datasets#preprocess_recognised'
      get  'unrecognised/:id',   to: 'import_datasets#unrecognised',
                                 as: :unrecognised
      post 'unrecognised/:id',   to: 'import_datasets#preprocess_unrecognised'
      get  'summary/:id',        to: 'import_datasets#summary',
                                 as: :summary
      post 'import/:id',         to: 'import_datasets#do_import'
      get  'abort_import(/:id)', to: 'import_datasets#abort_import',
                                 as: :abort_import
    end
    resource :datasets, only: [] do
      get  ':id/delete_confirmation', to: 'datasets#delete_confirmation',
        as: :delete_confirmation
    end
    resources :datasets
    resources :admin_users
    resource :admin_user, only: [] do
      get ':id/deactivate_confirmation', to: 'admin_users#deactivate_confirmation',
        as: :deactivate_confirmation
      put ':id/deactivate', to: 'admin_users#deactivate', as: :deactivate
      get ':id/reactivate_confirmation', to: 'admin_users#reactivate_confirmation',
        as: :reactivate_confirmation
      put ':id/reactivate', to: 'admin_users#reactivate', as: :reactivate
    end
    resources :uploads, only: %i[index]

    root to: 'home#index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope '(/:locale)', locale: /en|cy/, defaults: { locale: 'en' } do
    resources :categories,    only: %i[index show]
    resources :concepts,      only: %i[show]
    resources :data_elements, only: %i[show]
    resource :datasets,       only: [] do
      get 'data_elements/:id', to: 'datasets#data_elements'
    end
    resources :datasets,      only: %i[show]
    resources :search,        only: %i[index]
    resources :saved_items,   only: %i[index]
    resource :saved_items,    only: [] do
      post 'saved_items', to: 'saved_items#saved_items'
      post 'export_to_csv', to: 'saved_items#export_to_csv'
    end
  end
end

app/views/layouts/admin/_header_navigation.html.erb
<ul class="navbar-list govuk-body">
  <%- if main_app_root_path = (main_app.root_path rescue false) %>
    <li><%= link_to t('admin.links.public_site'), main_app_root_path %></li>
  <%- end %>
  <%- if current_admin_user %>
    <li>
      <%= link_to current_admin_user.email, main_app.edit_admin_user_registration_path(current_admin_user) %>
    </li>
    <li>
      <%= button_to t('admin.links.log_out'), main_app.destroy_admin_user_session_path, method: :delete, class: %w[button govuk-button--link] %>
    </li>
  <%- end %>
</ul>

app/views/layouts/admin/_navigation.html.erb
<%#
  # Navigation

  This partial is used to display the navigation in Administrate.
  By default, the navigation contains navigation links
  for all resources in the admin dashboard,
  as defined by the routes in the `admin/` namespace
%>

<nav class="navigation" role="navigation">
  <%= menu_links %>
</nav>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta name="robots" content="noodp, noydir, index, follow">
    <meta name="viewport" content="initial-scale=1">
    <title>
      <%= content_for(:title) || 'Dashboard' %> -
      <%= Rails.application.class.parent_name.titlecase %>
    </title>
    <%= javascript_pack_tag 'check_all' %>
    <%= javascript_pack_tag 'validate-forms' %>
    <%= javascript_pack_tag 'save_to_local_storage' %>
    <%= javascript_pack_tag 'administrate', 'data-turbolinks-track': 'reload' %>
    <%= render 'administrate/application/stylesheet' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'administrate' %>
    <%= stylesheet_pack_tag 'selectize_govuk' %>
    <%= csrf_meta_tags %>
    <%= yield :additional_tags %>
    <meta name="turbolinks-root" content="/admin">
  </head>
  <body class="govuk-template__body">
    <input type="hidden" id="timer-ms" value="<%= 1000 * (current_admin_user&.timeout_in&.seconds&.to_i || 1200) %>">
    <div class="app-pane app-pane--enabled">
      <%= render 'layouts/admin/government_header' %>
    </div>
    <div class="govuk-width-container">
      <%= render 'shared/staging' unless Rails.env.production? %>
      <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">
          <%= render "shared/breadcrumbs" %>
          <%= yield %>
        </div>
      </div>
    </div>
    <div class="icons" style="display: none; width: 0; height: 0; overflow: hidden; position: absolute">
      <%= render 'administrate/application/icons' %>
    </div>

    <%= render 'administrate/application/javascript' %>
    <%= render "shared/govuk_footer" %>
  </body>
</html>

app/views/layouts/admin/wide.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta name="robots" content="noodp, noydir, index, follow">
    <meta name="viewport" content="initial-scale=1">
    <title>
      <%= content_for(:title) || 'Dashboard' %> -
      <%= Rails.application.class.parent_name.titlecase %>
    </title>
    <%= javascript_pack_tag 'check_all' %>
    <%= javascript_pack_tag 'validate-forms' %>
    <%= javascript_pack_tag 'save_to_local_storage' %>
    <%= javascript_pack_tag 'administrate', 'data-turbolinks-track': 'reload' %>
    <%= render 'administrate/application/stylesheet' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'selectize_govuk' %>
    <%= csrf_meta_tags %>
    <%= yield :additional_tags %>
    <meta name="turbolinks-root" content="/admin">
  </head>
  <body class="govuk-template__body">
    <input type="hidden" id="timer-ms" value="<%= 1000 * (current_admin_user&.timeout_in&.seconds&.to_i || 1200) %>">
    <div class="app-pane app-pane--enabled">
      <%= render 'layouts/admin/government_header' %>
    </div>
    <div class="govuk-width-container">
      <%= render 'shared/staging' unless Rails.env.production? %>
      <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">
          <%= render "shared/breadcrumbs" %>
          <%= yield %>
        </div>
      </div>
    </div>
    <div class="icons" style="display: none; width: 0; height: 0; overflow: hidden; position: absolute">
      <%= render 'administrate/application/icons' %>
    </div>

    <%= render 'administrate/application/javascript' %>
    <%= render "shared/govuk_footer" %>
  </body>
</html>